FROM postgres:15

# Variáveis de ambiente do banco
ENV POSTGRES_DB=techback
ENV POSTGRES_USER=tech_user
ENV POSTGRES_PASSWORD=123456

# (Opcional) Scripts de inicialização
# COPY ./init.sql /docker-entrypoint-initdb.d/

EXPOSE 5432
