version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: meu_app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/techback
      SPRING_DATASOURCE_USERNAME: tech_user
      SPRING_DATASOURCE_PASSWORD: 123456
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      db:
        condition: service_healthy

  db:
    build:
      context: .
      dockerfile: Dockerfile-postgres
    container_name: meu_postgres
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tech_user -d techback"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db-data:
    driver: local
